import"./assets/styles-C18aTrnn.js";import{a as f}from"./assets/vendor-C19taMLP.js";const y="https://dummyjson.com";async function E(t){try{return(await f.get(`${y}/products/${t}`)).data}catch(o){console.log(o)}}async function w(t,o=1){try{return(await f.get(`${y}/products/search?q=${t}&limit=12&skip=${(o-1)*12}`)).data}catch(e){console.log(e)}}async function N(){try{return(await f.get(`${y}/products/category-list`)).data}catch(t){console.log(t)}}async function q(t,o=1){try{return(await f.get(`${y}/products/category/${t}?limit=12&skip=${(o-1)*12}`)).data}catch(e){console.log(e)}}async function M(t){try{return(await f.get(`${y}/products?limit=12&skip=${(t-1)*12}`)).data}catch(o){console.log(o)}}function h(t,o){const e=JSON.stringify(o);try{localStorage.setItem(t,e)}catch(r){console.error(r)}}function L(t){try{const o=localStorage.getItem(t);return o===null?void 0:JSON.parse(o)}catch(o){console.error(o)}}function a(t){return t.map(({id:o,title:e,category:r,images:c,description:_,brand:d,price:F})=>`
  <li class="products__item" data-id="${o}">
    <img class="products__image" src="${c[0]}" alt="${_}"/>
    <p class="products__title">${e}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${d}</span></p>
    <p class="products__category">Category: ${r}</p>
    <p class="products__price">Price: $${F}</p>
 </li>
  `).join("")}function j({returnPolicy:t,title:o,category:e,images:r,description:c,shippingInformation:_,price:d}){return`
<img class="modal-product__img" src="${r[0]}" alt="${c}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${o}</p>
        <ul class="modal-product__tags">${e}</ul>
        <p class="modal-product__description">${c}</p>
        <p class="modal-product__shipping-information">Shipping:${_}</p>
        <p class="modal-product__return-policy">Return Policy:${t}</p>
        <p class="modal-product__price">Price:${d}$</p>
      </div>

  `}D();let u="",n=0,l="All",p=0;const s=document.querySelector("ul.products"),k=document.querySelector("ul.categories"),v=document.querySelector("div.not-found");function D(){N().then(t=>{t.unshift("All");const o=t.map(e=>`
    <li class="categories__item">
   <button class="categories__btn" type="button">${e}</button>
 </li>
    `).join("");k.insertAdjacentHTML("beforeend",o),k.addEventListener("click",R)}).catch(t=>console.log(t))}async function R(t){if(t.target.nodeName!=="BUTTON")return;P(),u=t.target.textContent,u==="All"?l="All":l="category",k.querySelectorAll("button").forEach(r=>r.classList.remove("categories__btn--active")),t.target.closest("button").classList.add("categories__btn--active"),n=1;try{if(u==="All"){const c=await M(n);s.innerHTML=a(c.products),c.products.length>=12?$():m();return}const r=await q(u,n);r.products.length>=12?$():m(),s.innerHTML=a(r.products)}catch(r){console.log(r)}}function $(){g&&(g.style.display="block")}function m(){g&&(g.style.display="none")}s.addEventListener("click",z);const T=document.querySelector(".modal-product"),b=T.closest(".modal"),I=b.querySelector(".modal__close-btn");async function z(t){const o=t.target.closest(".products__item");if(o){p=o.dataset.id;try{const e=await E(p);T.innerHTML=j(e),b.classList.add("modal--is-open");const r=b.querySelector(".modal-product__btn--cart");(L("Cards")||[]).find(d=>d===p)?r.textContent="Remove from Cart":r.textContent="Add to cart",r.addEventListener("click",J)}catch(e){console.log(e)}}}I.addEventListener("click",O);function O(){b.classList.remove("modal--is-open")}const A=document.querySelector(".nav__count");let i=0;const B=L("cartCounter");B&&(i=B,A.textContent=i);function J(t){if(t.target.textContent==="Remove from Cart"){const r=(L("Cards")||[]).filter(c=>c!==p);h("Cards",r),i=A.textContent=r.length,h("cartCounter",i),t.target.textContent="Add to cart";return}t.target.textContent="Remove from Cart";const o=L("Cards")||[];o.push(p),h("Cards",o),i=A.textContent=[...o].length,h("cartCounter",i)}const H=document.querySelector(".search-form"),x=H.querySelector(".search-form__input");let C="";H.addEventListener("submit",U);async function U(t){t.preventDefault(),n=1,l="search",P();try{if(C=x.value.trim(),C==="")return;const o=await w(C,n);o.products.length>=12?$():m(),o.products.length===0&&(s.innerHTML="",v.classList.add("not-found--visible")),s.innerHTML=a(o.products)}catch(o){console.log(o)}}const V=document.querySelector(".search-form__btn-clear");V.addEventListener("click",G);async function G(){x.value="",l="All",P();const t=await M(n);s.innerHTML=a(t.products),t.products.length>=12?$():m()}const g=document.querySelector(".load-more-btn");g.addEventListener("click",K);async function K(){n+=1;try{if(l==="All"){const{products:t}=await M(n);S(t),s.insertAdjacentHTML("beforeend",a(t))}else if(l==="category"){const{products:t}=await q(u,n);S(t),s.insertAdjacentHTML("beforeend",a(t))}else if(l==="search"){const{products:t}=await w(C,n);S(t),s.insertAdjacentHTML("beforeend",a(t))}}catch(t){console.log(t)}}function S(t){t.length===0&&(v.classList.add("not-found--visible"),m())}function P(){v.classList.contains("not-found--visible")&&v.classList.remove("not-found--visible")}
//# sourceMappingURL=index.js.map
